[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
console = "0.16.2"
futures = "0.3.31"
futures-util = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
thiserror-ext = "0.3.0"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.28.0", features = ["rustls-tls-native-roots"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
registry = { path = "../registry" }
dirs = "6.0.0"
toml = "1.0.1"
url = "2.5.8"
